src/builtin/builtin_echo.c

refactor: use write_in_process in builtin_echo

---

src/builtin/builtin_pwd.c

refactor: use write_in_process:

---

src/builtin/builtin_exit.c

feat: builtin_exit, exit_status

---

src/builtin/builtin_export.c

feat: builtin_export

---

src/builtin/builtin_env.c

feat: builtin_env

---

src/builtin/builtin_unset.c

feat: builtin_unset

---

includes/lexer.h
src/lexer/lexer.c

refactor: TK_RESERVED -> TK_PROCESS_DELIMに変更，全体のリファクタ

---

src/builtin/builtin_echo.c

fix: builtin_echo -n

---

Makefile
includes/minishell.h
src/execution/execution.c
src/main/main.c

- main関数の実装
- signal(SIGINT,SIGQUIT)に対応
- shell_varの初期化
close #14

Main func #14

---

includes/execution.h
src/builtin/builtin_cd.c
src/execution/exec_processes.c
src/execution/exec_single_process.c
src/execution/get_fullpath_cmd.c
src/execution/set_heredoc.c

refactor: getenv から get_env_valueに変更

---

src/execution/exec_processes.c
src/execution/exec_single_process.c
src/execution/execution.c
src/execution/set_heredoc.c

refactor: set_heredoc, fix: dup2 in single_process

---

includes/execution.h
src/execution/exec_processes.c
src/execution/exec_single_process.c
src/execution/execution.c
src/execution/safe_func.c

feat: safe_func

---

includes/struct.h
src/execution/exec_processes.c
src/execution/exec_single_process.c
src/execution/set_heredoc.c

refactor: heredocを子プロセスで読み取る

---

src/execution/expansion_heredoc.c
src/execution/set_heredoc_utils.c
src/execution/set_redirections_and_commands.c

Redirections and commands #49

---

includes/execution.h
includes/utils.h
src/builtin/builtin_cd.c
src/builtin/builtin_exit.c
src/execution/exec_builtin.c
src/execution/exec_child.c
src/execution/exec_processes.c
src/execution/execution.c
src/execution/get_fullpath_cmd.c
src/execution/handle_fd.c
src/execution/set_redirections_and_commands.c
src/heredoc/expansion_heredoc.c
src/heredoc/set_heredoc.c
src/heredoc/set_heredoc_utils.c
src/utils/wrapper.c

style: norm

---

includes/expansion.h
src/expansion/convert_to_token_list.c
src/expansion/expansion.c
src/expansion/get_expansion_list.c

- normに対応するために1ファイル5関数以下1関数25行以下にしました．
- filename expansionは触ってないのでリーク対策はまだできていません．
close #50

Refactor expansion #50

---

src/analyzer/convert_to_expression_tree.c
src/analyzer/lexer.c
src/analyzer/parser.c
src/main/main.c

Refactor main analyzer for www #59

---

src/expansion/match_given_pattern.c

fix: asterisk_dp

---

includes/lexer.h
includes/parser.h
includes/utils.h
src/analyzer/lexer.c
src/analyzer/node_utils.c
src/analyzer/parser.c
src/analyzer/validate_line.c
src/utils/wrapper_str.c

- lexer.c, parser.cを分割しました．
- parser関数のparser_resultが長くて厄介だったので，(int)parser_result -> (bool)is_valid に変更しました．

Split lexer parser #63

---

includes/struct.h
includes/utils.h

style: norm struct.h utils.h

---

src/builtin/builtin_cd.c
src/main/main.c
src/utils/safe_func.c

Fix cd leak #76

---

src/expander/expand_token.c
src/main/main.c

issue #79 のコメントにあるエラーを修正
close #79

Fix analyzer #79

---

src/builtin/builtin_export.c
src/builtin/builtin_unset.c
src/env/set_env_value.c
src/expander/expand_token.c

issue#81のエラーに加えて，unsetの第２引数以降がスルーされているエラーを修正
close #81

fix: isuue#81のエラーを修正

---

includes/utils.h
src/executor/exec_processes.c
src/executor/exec_single_process.c
src/executor/get_fullpath_cmd.c
src/utils/handle_signal.c

Fix カレントディレクトリの実行ファイル #83

---

includes/shell_var.h
src/env/init_sh_var.c
src/main/main.c

- sh_var->pwdは$PWDで初期化する．
- $PWDがない場合は getcwd で初期化する．
上記修正しました．
close #85

fix: sh_var->pwdのinit方法

---

src/executor/get_fullpath_cmd.c

refactor: get_fullpath_cmdで .. のみの時はcommand not found

---

src/heredoc/set_heredoc.c

refactor: initialize in_quote in heredoc_child

---

src/builtin/builtin_exit.c

refactor: exit ending with space

---

src/executor/handle_fd.c
src/executor/set_io_params.c

Pipe fifo #108

---

src/builtin/builtin_echo.c
src/builtin/builtin_export.c
src/builtin/builtin_unset.c

refactor: builtinでitrではなくcommandのindexをプラスしていく

---

includes/utils.h
src/executor/exec_child.c
src/executor/exec_processes.c
src/heredoc/set_heredoc.c
src/main/main.c
src/utils/handle_signal.c

- `signal` 関数は処理系定義の動作を多く含むので `sigaction` を使う
- シグナルハンドラを非同期安全にする ( `sigint_handler` )
- `rl_signal_event_hook` 変数を用いて，signal受け取り後にプロンプトを再表示するようにした．
- heredoc後のシグナルハンドラを再設定した．
close #107

signalについて以下の通り変更しました
